// Central equipment catalog, seeded from the company's product spreadsheet.
// Loaded into equipment.json the first time the server runs against an empty
// store. Manage all of this from the admin page afterwards -- add real specs,
// product photos, and brochure links there; nothing here is meant to be final.
//
// NOTE: specs are intentionally empty -- the source spreadsheet only had
// Make/Model, no capacity/power/dimension data. Don't invent numbers for a
// sales tool; add real specs via the admin form once available.

const CATEGORIES = [
  { id: "feeding", label: "Feeding" },
  { id: "crushing", label: "Crushing" },
  { id: "screening", label: "Screening" },
  { id: "conveying", label: "Conveying" },
  { id: "stockpiling", label: "Stockpiling" },
  { id: "washing", label: "Washing" },
  { id: "shredding", label: "Shredding & Grinding" },
  { id: "mixing", label: "Mixing" },
];

const EQUIPMENT = [
  {
    category: "screening",
    name: "683 Supertrak",
    model: "Terex Finlay",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "696 Supertrak (2 Deck)",
    model: "Terex Finlay",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "696 Supertrak (3 Deck)",
    model: "Terex Finlay",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "883+ Reclaimer",
    model: "Terex Finlay",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "883+ Spaleck Reclaimer",
    model: "Terex Finlay",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "883+ Triple Shaft Reclaimer",
    model: "Terex Finlay",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "893 Reclaimer",
    model: "Terex Finlay",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "984 Horizontal",
    model: "Terex Finlay",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "C-1540S Cone Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "C-1545P Cone Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "C-1545S Cone Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "C-1550+ Cone Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "I-120 Impactor",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "I-120RS Impactor",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "I-140 Impactor",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "I-140RS Impactor",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "J-1175 Jaw Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "J-1280 Jaw Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "J-1480 Jaw Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "LJ-130 Hybrid Jaw Crusher",
    model: "Terex Finlay",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Bison 35 Jaw Crusher",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Bison 120 Jaw Crusher",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Bison 160 Jaw Crusher",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Bison 280 Jaw Crusher",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Bison 340 Jaw Crusher",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Cobra 230 Impactor",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Cobra 230R Impactor",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Cobra 290 Impactor",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "crushing",
    name: "Cobra 290R Impactor",
    model: "Terex Evoquip",
    icon: "crusher",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Colt 600 Reclaimer",
    model: "Terex Evoquip",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Colt 800 Reclaimer",
    model: "Terex Evoquip",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Colt 1000 Reclaimer",
    model: "Terex Evoquip",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Colt 1600 Reclaimer",
    model: "Terex Evoquip",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "Harrier 220 Screener",
    model: "Terex Evoquip",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "Harrier 750 Screener",
    model: "Terex Evoquip",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "Falcon 1220 Inclinded Screen",
    model: "Terex Evoquip",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "Falcon 1230 Inclinded Screen",
    model: "Terex Evoquip",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "feeding",
    name: "HF10T Hopper Feeder",
    model: "Telestack",
    icon: "hopper",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "feeding",
    name: "HF520 Hopper Feeder",
    model: "Telestack",
    icon: "hopper",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "feeding",
    name: "HF820 Hopper Feeder",
    model: "Telestack",
    icon: "hopper",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "feeding",
    name: "HF24 Tracked Hopper Feeder",
    model: "Telestack",
    icon: "hopper",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TC420 Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TC424X Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TC624 Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TC624R Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TS36-140 Agg Stack",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TS42 Telescopic Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TS52 Telescopic Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TS58 Telescopic Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TS1542 Telescopic Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "LS5032E Wheeled Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "LS5032H Wheeled Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "LS6036E Wheeled Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "LS6036H Wheeled Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Origin C2000 Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "Origin C2000RT Tracked Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "RS424X Wheeled Stockpiler",
    model: "Telestack",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "mixing",
    name: "Telemix P2000T Pug Mill",
    model: "Telestack",
    icon: "mixer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "TDS820 Slow Speed Shredder",
    model: "Terex Ecotec",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "TDSV20 Medium Speed Shredder",
    model: "Terex Ecotec",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "TBG630 High Speed Shredder",
    model: "Terex Ecotec",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "TBG530T High Speed Shredder",
    model: "Terex Ecotec",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "TTS620T Trommel",
    model: "Terex Ecotec",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "screening",
    name: "Phoenix 3300 Trommel",
    model: "Terex Ecotec",
    icon: "screen",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "conveying",
    name: "TRS550 Spaleck Reclaimer",
    model: "Terex Ecotec",
    icon: "stacker",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "6800CT Horizontal Grinder",
    model: "CBI",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "6400CT Horizontal Grinder",
    model: "CBI",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "5800BT Horizontal Grinder",
    model: "CBI",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "shredding",
    name: "5400BT Horizontal Grinder",
    model: "CBI",
    icon: "shredder",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "AggreSand 206",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "AggreScalp",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "AggreScrub",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "FM120C Fines Master",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "T150 Bucket Wheel",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "M1400 Tracked Rinser",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "M1700 Tracked Rinser",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
  {
    category: "washing",
    name: "M2100 Tracked Rinser",
    model: "Terex Washing Systems",
    icon: "washer",
    specs: {},
    imagePath: null,
    brochureUrl: null,
  },
];

module.exports = { CATEGORIES, EQUIPMENT };
